name: data-updates
run-name: updating JSON data files
on: [push]
jobs:
  change-dates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: npm install -g typescript
      - run: npm install
      - run: npm install --save-dev @types/node
      - run: tsc "./.github/workflows/jsonDataUpdater.ts"
      - run: node "./.github/workflows/jsonDataUpdater.js"
      - run: git config --local user.name "JSON Data Updater"
      - run: git add *
      - run: git commit -m "Updated JSON data files"
